services:
    prestashop:
        image: prestashop/prestashop
        environment:
            - DB_SERVER=db
        ports:
            - 8080:80

    db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=admin
        ports:
            - 3307:3306